/*
 HTML5 Oyunlar 2016
*/
var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,m,g){if(g.get||g.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[m]=g.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var m=0;return $jscomp.iteratorPrototype(function(){return m<c.length?{done:!1,value:c[m++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(c,m){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var g=0,e={next:function(){if(g<c.length){var n=g++;return{value:m(n,c[n]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(c,m,g,e){if(m){g=$jscomp.global;c=c.split(".");for(e=0;e<c.length-1;e++){var n=c[e];n in g||(g[n]={});g=g[n]}c=c[c.length-1];e=g[c];m=m(e);m!=e&&null!=m&&$jscomp.defineProperty(g,c,{configurable:!0,writable:!0,value:m})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6-impl","es3");
(function(c,m){function g(){var a=x.elements;return"string"==typeof a?a.split(" "):a}function e(a){var d=w[a._html5shiv];d||(d={},u++,a._html5shiv=u,w[u]=d);return d}function n(a,d,b){d||(d=m);if(q)return d.createElement(a);b||(b=e(d));d=b.cache[a]?b.cache[a].cloneNode():z.test(a)?(b.cache[a]=b.createElem(a)).cloneNode():b.createElem(a);return!d.canHaveChildren||v.test(a)||d.tagUrn?d:b.frag.appendChild(d)}function k(a,d){d.cache||(d.cache={},d.createElem=a.createElement,d.createFrag=a.createDocumentFragment,
d.frag=d.createFrag());a.createElement=function(b){return x.shivMethods?n(b,a,d):d.createElem(b)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+g().join().replace(/[\w\-:]+/g,function(a){d.createElem(a);d.frag.createElement(a);return'c("'+a+'")'})+");return n}")(x,d.frag)}function t(a){a||(a=m);var d=e(a);if(x.shivCSS&&!A&&!d.hasCSS){var b,c=a;b=c.createElement("p");c=c.getElementsByTagName("head")[0]||c.documentElement;b.innerHTML=
"x<style>article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}</style>";b=c.insertBefore(b.lastChild,c.firstChild);d.hasCSS=!!b}q||k(a,d);return a}var r=c.html5||{},v=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,z=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,A,u=0,w={},q;(function(){try{var a=m.createElement("a");a.innerHTML=
"<xyz></xyz>";A="hidden"in a;var d;if(!(d=1==a.childNodes.length)){m.createElement("a");var b=m.createDocumentFragment();d="undefined"==typeof b.cloneNode||"undefined"==typeof b.createDocumentFragment||"undefined"==typeof b.createElement}q=d}catch(D){q=A=!0}})();var x={elements:r.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output picture progress section summary template time video",version:"3.7.2",shivCSS:!1!==
r.shivCSS,supportsUnknownElements:q,shivMethods:!1!==r.shivMethods,type:"default",shivDocument:t,createElement:n,createDocumentFragment:function(a,d){a||(a=m);if(q)return a.createDocumentFragment();d=d||e(a);for(var b=d.frag.cloneNode(),c=0,k=g(),n=k.length;c<n;c++)b.createElement(k[c]);return b},addElements:function(a,c){var b=x.elements;"string"!=typeof b&&(b=b.join(" "));"string"!=typeof a&&(a=a.join(" "));x.elements=b+" "+a;t(c)}};c.html5=x;t(m)})(this,document);/*
 BloggerEklentileri.blogspot.com
*/
(function(c,m){"function"===typeof define&&define.amd?define(m):"object"===typeof exports?module.exports=m():c.returnExports=m()})(this,function(){function c(f){f=+f;f!==f?f=0:0!==f&&f!==1/0&&f!==-(1/0)&&(f=(0<f||-1)*Math.floor(Math.abs(f)));return f}function m(f){var h=typeof f;return null===f||"undefined"===h||"boolean"===h||"number"===h||"string"===h}function g(){}var e=Array.prototype,n=Object.prototype,k=Function.prototype,t=String.prototype,r=Number.prototype,v=e.slice,z=e.splice,A=e.unshift,
u=k.call,w=n.toString,q=function(f){return"[object Function]"===n.toString.call(f)},x=function(f){return"[object Array]"===w.call(f)},a=function(f){return"[object String]"===w.call(f)},d=function(f){var h="[object Arguments]"===w.call(f);h||(h=!x(f)&&null!==f&&"object"===typeof f&&"number"===typeof f.length&&0<=f.length&&q(f.callee));return h},b;if(b=Object.defineProperty)try{Object.defineProperty({},"x",{}),b=!0}catch(f){b=!1}var D;D=b?function(f,h,l,a){!a&&h in f||Object.defineProperty(f,h,{configurable:!0,
enumerable:!1,writable:!0,value:l})}:function(f,h,l,a){!a&&h in f||(f[h]=l)};b=function(f,h,l){for(var a in h)n.hasOwnProperty.call(h,a)&&D(f,a,h[a],l)};var B=function(f){if(null==f)throw new TypeError("can't convert "+f+" to object");return Object(f)};b(k,{bind:function(f){var h=this;if(!q(h))throw new TypeError("Function.prototype.bind called on incompatible "+h);for(var l=v.call(arguments,1),a=Math.max(0,h.length-l.length),b=[],c=0;c<a;c++)b.push("$"+c);var d=Function("binder","return function ("+
b.join(",")+"){return binder.apply(this,arguments)}")(function(){if(this instanceof d){var a=h.apply(this,l.concat(v.call(arguments)));return Object(a)===a?a:this}return h.apply(f,l.concat(v.call(arguments)))});h.prototype&&(g.prototype=h.prototype,d.prototype=new g,g.prototype=null);return d}});var E=u.bind(n.hasOwnProperty);E(n,"__defineGetter__")&&(u.bind(n.__defineGetter__),u.bind(n.__defineSetter__),u.bind(n.__lookupGetter__),u.bind(n.__lookupSetter__));k=function(){var f=[1,2],h=f.splice();
return 2===f.length&&x(h)&&0===h.length}();b(e,{splice:function(f,h){return 0===arguments.length?[]:z.apply(this,arguments)}},k);k=function(){var f={};e.splice.call(f,0,0,1);return 1===f.length}();b(e,{splice:function(f,h){if(0===arguments.length)return[];var a=arguments;this.length=Math.max(c(this.length),0);0<arguments.length&&"number"!==typeof h&&(a=v.call(arguments),2>a.length?a.push(this.length-f):a[1]=c(h));return z.apply(this,a)}},!k);k=1!==[].unshift(0);b(e,{unshift:function(){A.apply(this,
arguments);return this.length}},k);b(Array,{isArray:x});var k=Object("a"),C="a"!==k[0]||!(0 in k),k=function(f){var h=!0,a=!0;f&&(f.call("foo",function(a,f,l){"object"!==typeof l&&(h=!1)}),f.call([1],function(){a="string"===typeof this},"x"));return!!f&&h&&a};b(e,{forEach:function(f,h){var l=B(this),y=C&&a(this)?this.split(""):l,c=-1,b=y.length>>>0;if(!q(f))throw new TypeError;for(;++c<b;)c in y&&f.call(h,y[c],c,l)}},!k(e.forEach));b(e,{map:function(f,h){var l=B(this),y=C&&a(this)?this.split(""):
l,c=y.length>>>0,b=Array(c);if(!q(f))throw new TypeError(f+" is not a function");for(var d=0;d<c;d++)d in y&&(b[d]=f.call(h,y[d],d,l));return b}},!k(e.map));b(e,{filter:function(f,h){var l=B(this),y=C&&a(this)?this.split(""):l,c=y.length>>>0,b=[],d;if(!q(f))throw new TypeError(f+" is not a function");for(var e=0;e<c;e++)e in y&&(d=y[e],f.call(h,d,e,l)&&b.push(d));return b}},!k(e.filter));b(e,{every:function(f,h){var l=B(this),y=C&&a(this)?this.split(""):l,c=y.length>>>0;if(!q(f))throw new TypeError(f+
" is not a function");for(var b=0;b<c;b++)if(b in y&&!f.call(h,y[b],b,l))return!1;return!0}},!k(e.every));b(e,{some:function(f,h){var l=B(this),b=C&&a(this)?this.split(""):l,c=b.length>>>0;if(!q(f))throw new TypeError(f+" is not a function");for(var d=0;d<c;d++)if(d in b&&f.call(h,b[d],d,l))return!0;return!1}},!k(e.some));k=!1;e.reduce&&(k="object"===typeof e.reduce.call("es5",function(a,h,l,b){return b}));b(e,{reduce:function(f){var h=B(this),l=C&&a(this)?this.split(""):h,b=l.length>>>0;if(!q(f))throw new TypeError(f+
" is not a function");if(!b&&1===arguments.length)throw new TypeError("reduce of empty array with no initial value");var c=0,d;if(2<=arguments.length)d=arguments[1];else{do{if(c in l){d=l[c++];break}if(++c>=b)throw new TypeError("reduce of empty array with no initial value");}while(1)}for(;c<b;c++)c in l&&(d=f.call(void 0,d,l[c],c,h));return d}},!k);k=!1;e.reduceRight&&(k="object"===typeof e.reduceRight.call("es5",function(a,h,l,b){return b}));b(e,{reduceRight:function(f){var h=B(this),l=C&&a(this)?
this.split(""):h,b=l.length>>>0;if(!q(f))throw new TypeError(f+" is not a function");if(!b&&1===arguments.length)throw new TypeError("reduceRight of empty array with no initial value");var c,b=b-1;if(2<=arguments.length)c=arguments[1];else{do{if(b in l){c=l[b--];break}if(0>--b)throw new TypeError("reduceRight of empty array with no initial value");}while(1)}if(0>b)return c;do b in l&&(c=f.call(void 0,c,l[b],b,h));while(b--);return c}},!k);k=Array.prototype.indexOf&&-1!==[0,1].indexOf(1,2);b(e,{indexOf:function(f){var h=
C&&a(this)?this.split(""):B(this),l=h.length>>>0;if(!l)return-1;var b=0;1<arguments.length&&(b=c(arguments[1]));for(b=0<=b?b:Math.max(0,l+b);b<l;b++)if(b in h&&h[b]===f)return b;return-1}},k);k=Array.prototype.lastIndexOf&&-1!==[0,1].lastIndexOf(0,-3);b(e,{lastIndexOf:function(f){var h=C&&a(this)?this.split(""):B(this),b=h.length>>>0;if(!b)return-1;var d=b-1;1<arguments.length&&(d=Math.min(d,c(arguments[1])));for(d=0<=d?d:b-Math.abs(d);0<=d;d--)if(d in h&&f===h[d])return d;return-1}},k);var F=!{toString:null}.propertyIsEnumerable("toString"),
I=function(){}.propertyIsEnumerable("prototype"),G="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),J=G.length;b(Object,{keys:function(f){var h=q(f),b=d(f),c=null!==f&&"object"===typeof f,e=c&&a(f);if(!c&&!h&&!b)throw new TypeError("Object.keys called on a non-object");c=[];h=I&&h;if(e||b)for(b=0;b<f.length;++b)c.push(String(b));else for(var g in f)h&&"prototype"===g||!E(f,g)||c.push(String(g));if(F)for(b=(b=f.constructor)&&b.prototype===f,
e=0;e<J;e++)g=G[e],b&&"constructor"===g||!E(f,g)||c.push(g);return c}});var k=Object.keys&&function(){return 2===Object.keys(arguments).length}(1,2),H=Object.keys;b(Object,{keys:function(a){return d(a)?H(e.slice.call(a)):H(a)}},!k);k=Date.prototype.toISOString&&-1===(new Date(-621987552E5)).toISOString().indexOf("-000001");b(Date.prototype,{toISOString:function(){var a,h,b,c;if(!isFinite(this))throw new RangeError("Date.prototype.toISOString called on non-finite value.");c=this.getUTCFullYear();a=
this.getUTCMonth();c+=Math.floor(a/12);a=[(a%12+12)%12+1,this.getUTCDate(),this.getUTCHours(),this.getUTCMinutes(),this.getUTCSeconds()];c=(0>c?"-":9999<c?"+":"")+("00000"+Math.abs(c)).slice(0<=c&&9999>=c?-4:-6);for(h=a.length;h--;)b=a[h],10>b&&(a[h]="0"+b);return c+"-"+a.slice(0,2).join("-")+"T"+a.slice(2).join(":")+"."+("000"+this.getUTCMilliseconds()).slice(-3)+"Z"}},k);k=!1;try{k=Date.prototype.toJSON&&null===(new Date(NaN)).toJSON()&&-1!==(new Date(-621987552E5)).toJSON().indexOf("-000001")&&
Date.prototype.toJSON.call({toISOString:function(){return!0}})}catch(f){}k||(Date.prototype.toJSON=function(a){a=Object(this);var b;a:if(m(a))b=a;else{b=a.valueOf;if(q(b)&&(b=b.call(a),m(b)))break a;b=a.toString;if(q(b)&&(b=b.call(a),m(b)))break a;throw new TypeError;}if("number"===typeof b&&!isFinite(b))return null;b=a.toISOString;if("function"!==typeof b)throw new TypeError("toISOString property is not callable");return b.call(a)});var k=1E15===Date.parse("+033658-09-27T01:46:40.000Z"),u=!isNaN(Date.parse("2012-04-04T24:00:00.500Z"))||
!isNaN(Date.parse("2012-11-31T23:59:59.000Z")),M=isNaN(Date.parse("2000-01-01T00:00:00.000Z"));if(!Date.parse||M||u||!k)Date=function(a){function b(c,h,d,l,f,e,g){var k=arguments.length;return this instanceof a?(k=1===k&&String(c)===c?new a(b.parse(c)):7<=k?new a(c,h,d,l,f,e,g):6<=k?new a(c,h,d,l,f,e):5<=k?new a(c,h,d,l,f):4<=k?new a(c,h,d,l):3<=k?new a(c,h,d):2<=k?new a(c,h):1<=k?new a(c):new a,k.constructor=b,k):a.apply(this,arguments)}function c(a,b){var c=1<b?1:0;return f[b]+Math.floor((a-1969+
c)/4)-Math.floor((a-1901+c)/100)+Math.floor((a-1601+c)/400)+365*(a-1970)}var d=/^(\d{4}|[+-]\d{6})(?:-(\d{2})(?:-(\d{2})(?:T(\d{2}):(\d{2})(?::(\d{2})(?:(\.\d{1,}))?)?(Z|(?:([-+])(\d{2}):(\d{2})))?)?)?)?$/,f=[0,31,59,90,120,151,181,212,243,273,304,334,365],e;for(e in a)b[e]=a[e];b.now=a.now;b.UTC=a.UTC;b.prototype=a.prototype;b.prototype.constructor=b;b.parse=function(b){var h=d.exec(b);if(h){var l=Number(h[1]),f=Number(h[2]||1)-1,e=Number(h[3]||1)-1,g=Number(h[4]||0),k=Number(h[5]||0),p=Number(h[6]||
0),y=Math.floor(1E3*Number(h[7]||0)),m=!(!h[4]||h[8]),H="-"===h[9]?1:-1,n=Number(h[10]||0),h=Number(h[11]||0);return g<(0<k||0<p||0<y?24:25)&&60>k&&60>p&&1E3>y&&-1<f&&12>f&&24>n&&60>h&&-1<e&&e<c(l,f+1)-c(l,f)&&(l=60*(24*(c(l,f)+e)+g+n*H),l=1E3*(60*(l+k+h*H)+p)+y,m&&(l=Number(new a(1970,0,1,0,0,0,l))),-864E13<=l&&864E13>=l)?l:NaN}return a.parse.apply(this,arguments)};return b}(Date);Date.now||(Date.now=function(){return(new Date).getTime()});var k=r.toFixed&&("0.000"!==(8E-5).toFixed(3)||"1"!==(.9).toFixed(0)||
"1.25"!==(1.255).toFixed(2)||"1000000000000000128"!==(0xde0b6b3a7640080).toFixed(0)),p={base:1E7,size:6,data:[0,0,0,0,0,0],multiply:function(a,b){for(var c=-1;++c<p.size;)b+=a*p.data[c],p.data[c]=b%p.base,b=Math.floor(b/p.base)},divide:function(a){for(var b=p.size,c=0;0<=--b;)c+=p.data[b],p.data[b]=Math.floor(c/a),c=c%a*p.base},numToString:function(){for(var a=p.size,b="";0<=--a;)if(""!==b||0===a||0!==p.data[a])var c=String(p.data[a]),b=""===b?c:b+("0000000".slice(0,7-c.length)+c);return b},pow:function h(a,
b,c){return 0===b?c:1===b%2?h(a,b-1,c*a):h(a*a,b/2,c)},log:function(a){for(var b=0;4096<=a;)b+=12,a/=4096;for(;2<=a;)b+=1,a/=2;return b}};b(r,{toFixed:function(a){var b,c,d;a=Number(a);a=a!==a?0:Math.floor(a);if(0>a||20<a)throw new RangeError("Number.toFixed called with invalid number of decimals");b=Number(this);if(b!==b)return"NaN";if(-1E21>=b||1E21<=b)return String(b);c="";0>b&&(c="-",b=-b);d="0";if(1E-21<b)if(d=p.log(b*p.pow(2,69,1))-69,b=0>d?b*p.pow(2,-d,1):b/p.pow(2,d,1),b*=4503599627370496,
d=52-d,0<d){p.multiply(0,b);for(b=a;7<=b;)p.multiply(1E7,0),b-=7;p.multiply(p.pow(10,b,1),0);for(b=d-1;23<=b;)p.divide(8388608),b-=23;p.divide(1<<b);p.multiply(1,1);p.divide(2);d=p.numToString()}else p.multiply(0,b),p.multiply(1<<-d,0),d=p.numToString()+"0.00000000000000000000".slice(2,2+a);0<a?(b=d.length,d=b<=a?c+"0.0000000000000000000".slice(0,a-b+2)+d:c+d.slice(0,b-a)+"."+d.slice(b-a)):d=c+d;return d}},k);var K=t.split;2!=="ab".split(/(?:ab)*/).length||4!==".".split(/(.?)(.?)/).length||"t"===
"tesst".split(/(s)*/)[1]||4!=="test".split(/(?:)/,-1).length||"".split(/.?/).length||1<".".split(/()()/).length?function(){var b=void 0===/()??/.exec("")[1];t.split=function(a,c){var d=this;if(void 0===a&&0===c)return[];if("[object RegExp]"!==w.call(a))return K.call(this,a,c);var h=[],l=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.extended?"x":"")+(a.sticky?"y":""),g=0,k,p,m;a=new RegExp(a.source,l+"g");d+="";b||(k=new RegExp("^"+a.source+"$(?!\\s)",l));for(c=void 0===c?4294967295:c>>>0;p=a.exec(d);){l=
p.index+p[0].length;if(l>g&&(h.push(d.slice(g,p.index)),!b&&1<p.length&&p[0].replace(k,function(){for(var a=1;a<arguments.length-2;a++)void 0===arguments[a]&&(p[a]=void 0)}),1<p.length&&p.index<d.length&&e.push.apply(h,p.slice(1)),m=p[0].length,g=l,h.length>=c))break;a.lastIndex===p.index&&a.lastIndex++}g===d.length?!m&&a.test("")||h.push(""):h.push(d.slice(g));return h.length>c?h.slice(0,c):h}}():"0".split(void 0,0).length&&(t.split=function(a,b){return void 0===a&&0===b?[]:K.call(this,a,b)});var L=
t.replace;(function(){var a=[];"x".replace(/x(.)?/g,function(b,c){a.push(c)});return 1===a.length&&"undefined"===typeof a[0]})()||(t.replace=function(a,b){var c=q(b),d="[object RegExp]"===n.toString.call(a)&&/\)[*?]/.test(a.source);return c&&d?L.call(this,a,function(c){var d=arguments.length,h=a.lastIndex;a.lastIndex=0;var e=a.exec(c);a.lastIndex=h;e.push(arguments[d-2],arguments[d-1]);return b.apply(this,e)}):L.call(this,a,b)});var N=t.substr,r="".substr&&"b"!=="0b".substr(-1);b(t,{substr:function(a,
b){return N.call(this,0>a?0>(a=this.length+a)?0:a:a,b)}},r);var O=RegExp("^[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff][\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff]*"),P=RegExp("[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff][\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff]*$"),
r=t.trim&&("\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff".trim()||!"\u200b".trim());b(t,{trim:function(){if(void 0===this||null===this)throw new TypeError("can't convert "+this+" to object");return String(this).replace(O,"").replace(P,"")}},r);if(8!==parseInt("\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff08")||22!==parseInt("\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff0x16"))parseInt=
function(a){var b=/^0[xX]/;return function(c,d){c=String(c).trim();Number(d)||(d=b.test(c)?16:10);return a(c,d)}}(parseInt)});(function(c,m){"function"===typeof define&&define.amd?define(m):"object"===typeof exports?module.exports=m():c.returnExports=m()})(this,function(){function c(a){try{return a.sentinel=0,0===Object.getOwnPropertyDescriptor(a,"sentinel").value}catch(d){}}function m(a){try{return Object.defineProperty(a,"sentinel",{}),"sentinel"in a}catch(d){}}var g=Function.prototype.call,e=Object.prototype,n=g.bind(e.hasOwnProperty),k,t,r,v,z=n(e,"__defineGetter__");z&&(k=g.bind(e.__defineGetter__),t=g.bind(e.__defineSetter__),
r=g.bind(e.__lookupGetter__),v=g.bind(e.__lookupSetter__));Object.getPrototypeOf||(Object.getPrototypeOf=function(a){var c=a.__proto__;return c||null===c?c:a.constructor?a.constructor.prototype:e});if(Object.defineProperty&&(g=c({}),"undefined"!==typeof document&&!c(document.createElement("div"))||!g))var A=Object.getOwnPropertyDescriptor;if(!Object.getOwnPropertyDescriptor||A)Object.getOwnPropertyDescriptor=function(a,c){if("object"!==typeof a&&"function"!==typeof a||null===a)throw new TypeError("Object.getOwnPropertyDescriptor called on a non-object: "+
a);if(A)try{return A.call(Object,a,c)}catch(F){}if(n(a,c)){var b={enumerable:!0,configurable:!0};if(z){var d=a.__proto__,g=a!==e;g&&(a.__proto__=e);var k=r(a,c),m=v(a,c);g&&(a.__proto__=d);if(k||m)return k&&(b.get=k),m&&(b.set=m),b}b.value=a[c];b.writable=!0;return b}};Object.getOwnPropertyNames||(Object.getOwnPropertyNames=function(a){return Object.keys(a)});if(!Object.create){var u;u="undefined"===typeof document?function(){return{__proto__:null}}:function(){function a(){}var c=document.createElement("iframe"),
b=document.body||document.documentElement;c.style.display="none";b.appendChild(c);c.src="javascript:";var e=c.contentWindow.Object.prototype;b.removeChild(c);c=null;delete e.constructor;delete e.hasOwnProperty;delete e.propertyIsEnumerable;delete e.isPrototypeOf;delete e.toLocaleString;delete e.toString;delete e.valueOf;e.__proto__=null;a.prototype=e;u=function(){return new a};return new a};Object.create=function(a,c){function b(){}var d;if(null===a)d=u();else{if("object"!==typeof a&&"function"!==
typeof a)throw new TypeError("Object prototype may only be an Object or null");b.prototype=a;d=new b;d.__proto__=a}void 0!==c&&Object.defineProperties(d,c);return d}}if(Object.defineProperty){var g=m({}),w="undefined"===typeof document||m(document.createElement("div"));if(!g||!w)var q=Object.defineProperty,x=Object.defineProperties}if(!Object.defineProperty||q)Object.defineProperty=function(a,c,b){if("object"!==typeof a&&"function"!==typeof a||null===a)throw new TypeError("Object.defineProperty called on non-object: "+
a);if("object"!==typeof b&&"function"!==typeof b||null===b)throw new TypeError("Property description must be an object: "+b);if(q)try{return q.call(Object,a,c,b)}catch(B){}if(n(b,"value"))if(z&&(r(a,c)||v(a,c))){var d=a.__proto__;a.__proto__=e;delete a[c];a[c]=b.value;a.__proto__=d}else a[c]=b.value;else{if(!z)throw new TypeError("getters & setters can not be defined on this javascript engine");n(b,"get")&&k(a,c,b.get);n(b,"set")&&t(a,c,b.set)}return a};if(!Object.defineProperties||x)Object.defineProperties=
function(a,c){if(x)try{return x.call(Object,a,c)}catch(D){}for(var b in c)n(c,b)&&"__proto__"!==b&&Object.defineProperty(a,b,c[b]);return a};Object.seal||(Object.seal=function(a){return a});Object.freeze||(Object.freeze=function(a){return a});try{Object.freeze(function(){})}catch(a){Object.freeze=function(a){return function(b){return"function"===typeof b?b:a(b)}}(Object.freeze)}Object.preventExtensions||(Object.preventExtensions=function(a){return a});Object.isSealed||(Object.isSealed=function(a){return!1});
Object.isFrozen||(Object.isFrozen=function(a){return!1});Object.isExtensible||(Object.isExtensible=function(a){if(Object(a)!==a)throw new TypeError;for(var c="";n(a,c);)c+="?";a[c]=!0;var b=n(a,c);delete a[c];return b})});(function(c,m){var g=c.Event.prototype,e=c.Element.prototype,n=c.HTMLDocument,k=c.Window,t=[],r=function(e,g){var k=this,n=function(a){a.target=a.srcElement;a.currentTarget=k;g.handleEvent?g.handleEvent(a):g.call(k,a)},q,r;"DOMContentLoaded"===e?(q=function(a){"complete"===m.readyState&&n(a)},m.attachEvent("onreadystatechange",q),t.push({object:this,type:e,listener:g,wrapper:q}),"complete"===m.readyState&&(r=new c.Event,r.srcElement=c,q(r))):(this.attachEvent("on"+e,n),t.push({object:this,type:e,
listener:g,wrapper:n}))},v=function(c,e){for(var g=0,k;g<t.length;){k=t[g];if(k.object===this&&k.type===c&&k.listener===e){"DOMContentLoaded"===c?this.detachEvent("onreadystatechange",k.wrapper):this.detachEvent("on"+c,k.wrapper);t.splice(g,1);break}++g}};g.preventDefault||(g.preventDefault=function(){this.returnValue=!1});g.stopPropagation||(g.stopPropagation=function(){this.cancelBubble=!0});e.addEventListener||(e.addEventListener=r,e.removeEventListener=v,n&&(n.prototype.addEventListener=r,n.prototype.removeEventListener=
v),k&&(k.prototype.addEventListener=r,k.prototype.removeEventListener=v))})(window,document);(function(c){function m(){E(!0)}var g={};c.respond=g;g.update=function(){};var e=[],n=function(){var a=!1;try{a=new c.XMLHttpRequest}catch(J){a=new c.ActiveXObject("Microsoft.XMLHTTP")}return function(){return a}}(),k=function(a,b){var c=n();c&&(c.open("GET",a,!0),c.onreadystatechange=function(){4!==c.readyState||200!==c.status&&304!==c.status||b(c.responseText)},4!==c.readyState&&c.send(null))},t=function(a){return a.replace(g.regex.minmaxwh,"").match(g.regex.other)};g.ajax=k;g.queue=e;g.unsupportedmq=
t;g.regex={media:/@media[^\{]+\{([^\{\}]*\{[^\}\{]*\})+/gi,keyframes:/@(?:\-(?:o|moz|webkit)\-)?keyframes[^\{]+\{(?:[^\{\}]*\{[^\}\{]*\})+[^\}]*\}/gi,comments:/\/\*[^*]*\*+([^/][^*]*\*+)*\//gi,urls:/(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,findStyles:/@media *([^\{]+)\{([\S\s]+?)$/,only:/(only\s+)?([a-zA-Z]+)\s?/,minw:/\(\s*min\-width\s*:\s*(\s*[0-9\.]+)(px|em)\s*\)/,maxw:/\(\s*max\-width\s*:\s*(\s*[0-9\.]+)(px|em)\s*\)/,minmaxwh:/\(\s*m(in|ax)\-(height|width)\s*:\s*(\s*[0-9\.]+)(px|em)\s*\)/gi,
other:/\([^\)]*\)/g};g.mediaQueriesSupported=c.matchMedia&&null!==c.matchMedia("only all")&&c.matchMedia("only all").matches;if(!g.mediaQueriesSupported){var r=c.document,v=r.documentElement,z=[],A=[],u=[],w={},q=r.getElementsByTagName("head")[0]||v,x=r.getElementsByTagName("base")[0],a=q.getElementsByTagName("link"),d,b,D,B=function(){var a,b=r.createElement("div"),c=r.body,d=v.style.fontSize,e=c&&c.style.fontSize,g=!1;b.style.cssText="position:absolute;font-size:1em;width:1em";c||(c=g=r.createElement("body"),
c.style.background="none");c.appendChild(b);g&&v.insertBefore(c,v.firstChild);a=b.offsetWidth;g?v.removeChild(c):c.removeChild(b);v.style.fontSize=d;e&&(c.style.fontSize=e);return a=D=parseFloat(a)},E=function(e){var g=v.clientWidth,k="CSS1Compat"===r.compatMode&&g||r.body.clientWidth||g,g={},m=a[a.length-1],p=(new Date).getTime();if(e&&d&&30>p-d)c.clearTimeout(b),b=c.setTimeout(E,30);else{d=p;for(var n in z)if(z.hasOwnProperty(n)){e=z[n];var p=e.minw,t=e.maxw,x=null===p,G=null===t;p&&(p=parseFloat(p)*
(-1<p.indexOf("em")?D||B():1));t&&(t=parseFloat(t)*(-1<t.indexOf("em")?D||B():1));e.hasquery&&(x&&G||!(x||k>=p)||!(G||k<=t))||(g[e.media]||(g[e.media]=[]),g[e.media].push(A[e.rules]))}for(var w in u)u.hasOwnProperty(w)&&u[w]&&u[w].parentNode===q&&q.removeChild(u[w]);u.length=0;for(var f in g)g.hasOwnProperty(f)&&(n=r.createElement("style"),w=g[f].join("\n"),n.type="text/css",n.media=f,q.insertBefore(n,m.nextSibling),n.styleSheet?n.styleSheet.cssText=w:n.appendChild(r.createTextNode(w)),u.push(n))}},
C=function(a,b,c){var d=a.replace(g.regex.comments,"").replace(g.regex.keyframes,"").match(g.regex.media),e=d&&d.length||0;b=b.substring(0,b.lastIndexOf("/"));var k=!e&&c;b.length&&(b+="/");k&&(e=1);for(var n=0;n<e;n++){var m,q,r;k?(m=c,A.push(a.replace(g.regex.urls,"$1"+b+"$2$3"))):(m=d[n].match(g.regex.findStyles)&&RegExp.$1,A.push(RegExp.$2&&RegExp.$2.replace(g.regex.urls,"$1"+b+"$2$3")));q=m.split(",");r=q.length;for(var f=0;f<r;f++)m=q[f],t(m)||z.push({media:m.split("(")[0].match(g.regex.only)&&
RegExp.$2||"all",rules:A.length-1,hasquery:-1<m.indexOf("("),minw:m.match(g.regex.minw)&&parseFloat(RegExp.$1)+(RegExp.$2||""),maxw:m.match(g.regex.maxw)&&parseFloat(RegExp.$1)+(RegExp.$2||"")})}E()},F=function(){if(e.length){var a=e.shift();k(a.href,function(b){C(b,a.href,a.media);w[a.href]=!0;c.setTimeout(function(){F()},0)})}},I=function(){for(var b=0;b<a.length;b++){var d=a[b],g=d.href,k=d.media,m=d.rel&&"stylesheet"===d.rel.toLowerCase();if(g&&m&&!w[g])if(d.styleSheet&&d.styleSheet.rawCssText)C(d.styleSheet.rawCssText,
g,k),w[g]=!0;else if(!/^([a-zA-Z:]*\/\/)/.test(g)&&!x||g.replace(RegExp.$1,"").split("/")[0]===c.location.host)"//"===g.substring(0,2)&&(g=c.location.protocol+g),e.push({href:g,media:k})}F()};I();g.update=I;g.getEmValue=B;c.addEventListener?c.addEventListener("resize",m,!1):c.attachEvent&&c.attachEvent("onresize",m)}})(this);