Html5Oyunlar({waiton:"Html5Oyunlar.loaded"},"SWPUtils SWP SWPEvent DOMSelect DOMEvent Placeholder".split(" "),function(f,b,q,l,c,k){b.init("popup_login");l.get("#popup-login-username")&&(k.init("popup-login-username"),k.init("popup-login-password"));var m=!1,g=0,r=document.createElement("div"),a=function(a){return document.getElementById(a)||r},h=function(e,b){var d=a("popup-login-error-generic"),c=a("popup-login-error-banned");e?"banned"==b?f.addClass(c,"visible"):f.addClass(d,"visible"):(f.removeClass(d,
"visible"),f.removeClass(c,"visible"))},d=function(e,t){g!==e&&2!==g&&(l.get("#popup-login-close")?(g=e,h(!1),a("popup-login-username").value="",a("popup-login-password").value="",a("popup-login-remember").checked=!0,1===e?(b.System.emit("gi.game.hide"),b.System.emit("popup.header.open"),f.removeClass(a("wdg_popup_login"),"hidden"),u(),/Trident/g.test(window.navigator.userAgent)||(document.getElementById("popup-login-username_ph")?c.trigger("#popup-login-username_ph","keydown"):a("popup-login-username").focus())):
(t||(b.System.emit("gi.game.show"),b.System.emit("popup.header.close")),b.System.emit("popup.closed",{type:"login"}),f.addClass(a("wdg_popup_login"),"hidden"))):(g=2,b.Widget.refresh({show_popup_contents:!0},{callback:function(){setTimeout(function(){k.init("popup-login-username");k.init("popup-login-password");g=0;d(1)},0)}})))},u=function(){!0!==m&&(m=!0,c.add(a("popup-login-form"),"submit",function(a){c.preventDefault(a);v()}),c.add(a("popup-login-close"),"click",function(){d(0)}),c.add(a("popup-login-facebook"),
"click",function(){n("facebook")}),c.add(a("popup-login-google"),"click",function(){n("google")}),c.add(a("popup-login-register"),"click",function(){d(0);b.System.emit("popup.register.open",{})}))},p=function(e){a("popup-login-button").enabled=e;f[e?"removeClass":"addClass"](a("popup-login-button"),"processing")},v=function(){if("undefined"===typeof a("popup-login-button").enabled||a("popup-login-button").enabled)h(!1),""===a("popup-login-password").value||""===a("popup-login-username").value?h(!0):
(b.System.emit("auth.login.request",{rememberMe:a("popup-login-remember").checked,username:a("popup-login-username").value,password:a("popup-login-password").value,callback:function(a){a.isError&&(a.scope&&a.scope.data&&"banned"==a.scope.data.string?h(!0,"banned"):h(!0),p(!0))}}),p(!1))},n=function(e){var c=a("popup-login-remember").checked;b.System.emit("auth.login.remember",{rememberMe:c});d(0);b.System.emit("popup.oauth.open",{provider:e})};"onload"===b.getProperty("requires_auth")&&q.listen("onDisplayGame",
function(){d(1)});b.System.init(function(a){switch(a.name){case "popup.login.open":0===g?d(1):d(0);break;case "popup.register.open":d(0,!0)}},!0)});
/* Games */
Html5Oyunlar({waiton:"Html5Oyunlar.loaded"},"SWPUtils SWP SWPEvent JSLib Cache DOMEvent SPAPI".split(" "),function(r,h,m,d,q,n,v){h.init("popup_oauth");var a={facebook:"Facebook",google:"Google+",test:"Test Provider"},k=!1,g=function(){var a=h.getProperty("show_popup_contents");return function(f){f=f||function(){};a?!0===a&&f():(a="loading",h.Widget.refresh({show_popup_contents:!0},{callback:function(){setTimeout(function(){a=!0;f()},0)}}))}}(),t=function(w,f){w||h.System.emit("popup.header.close");var d=
document.getElementById("popup-oauth-error"),k={generic:document.getElementById("popup-oauth-error-message-generic"),cannotLink:document.getElementById("popup-oauth-error-message-cannotLink")},g={"cannotLink-username":document.getElementById("popup-oauth-error-message-cannotLink-username"),"cannotLink-provider":document.getElementById("popup-oauth-error-message-cannotLink-provider"),"cannotLink-email":document.getElementById("popup-oauth-error-message-cannotLink-email"),"generic-close":document.getElementById("popup-oauth-error-message-generic-btn-close"),
"generic-tryagain":document.getElementById("popup-oauth-error-message-generic-btn-tryagain")};h.Utils.addClass(d,"hidden");switch(w){case "cannotLink":g["cannotLink-username"]&&(g["cannotLink-username"].innerHTML=f.username);g["cannotLink-provider"]&&(g["cannotLink-provider"].innerHTML=a[f.provider]);g["cannotLink-email"]&&(g["cannotLink-email"].innerHTML=a[f.email]);k.cannotLink.style.display="block";h.Utils.removeClass(d,"hidden");h.System.emit("popup.header.open");break;case "error":k.generic.style.display=
"block",f.provider?(g["generic-close"].style.display="none",g["generic-tryagain"].style.display="",g["generic-tryagain"].onclick=function(){h.Utils.addClass(d,"hidden");h.System.emit("popup.header.close");h.System.emit("popup.oauth.open",{provider:f.provider})}):(g["generic-tryagain"].style.display="",g["generic-close"].style.display=""),h.Utils.removeClass(d,"hidden"),h.System.emit("popup.header.open")}},x=function(d){var g=void 0!==window.location.origin?window.location.origin:"";k&&(k.close(),
k=!1);d in a&&(k=window.open(g+"/oauth/?provider="+d,"oauth","height=375,width=600,scrollbars=yes"))},u=function(a){if(k)switch(k.close(),k=!1,a.result){case "loggedIn":h.System.emit("login.finished",a);break;case "notLinkable":t("cannotLink",a);break;case "needData":h.Widget.emit("register.open",a);h.System.emit("popup.header.open");break;default:t("error",a)}};h.System.init(function(a){switch(a.name){case "popup.header.open":g();break;case "popup.oauth.open":g(function(){n.add("#popup-oauth-error .close-action",
"click",function(){t(!1)});var d=!1;"provider"in a.body&&(d=a.body.provider);x(d)});break;case "popup.oauth.close":g(function(){x(!1)})}});m.listen("oauth.result",function(a){a&&u(a)});n.add(window,"storage",function(a){a&&"oauth.data"==a.key&&a.newValue&&(a=JSON.parse(a.newValue).value)&&u(a)})});var oauthCallback=function(r){Html5Oyunlar(["SWPEvent"],function(h){h.emit("oauth.result",JSON.parse(r))})};Html5Oyunlar({waiton:"Html5Oyunlar.loaded"},"FormValidation JSLib SWP SWPUtils DOMEvent DOMSelect Placeholder".split(" "),function(r,h,m,d,q,n,v){m.init("popup_oauth");var a=function(a){return document.getElementById("popup-oauth-register"+(a?"-"+a:""))},k={},g={},t=0,x={facebook:"Facebook",google:"Google+",test:"Test Provider"},u=function(b){b||m.System.emit("popup.header.close");d[b?"removeClass":"addClass"](a("error-generic"),"hidden")},w=function(a,c,e){a&&(a.id="hint-sign-"+t++,q.add(a,"mouseover",
function(){d.hasClass(a,"wrong")||d.removeClass(c,"hidden")}),q.add(a,"mouseout",function(){d.addClass(c,"hidden")}));"object"===typeof e&&e.length||(e=[e]);for(var g=0;g<e.length;g++)q.add(e[g],"focus",function(){a&&!d.hasClass(a,"wrong")||d.removeClass(c,"hidden")}),q.add(e[g],"blur",function(){d.addClass(c,"hidden")})},f=function(a){d.addClass(a,"hidden")},p=function(a){d.removeClass(a,"hidden")},y=function(){a("username").value="";a("email").value="";a("password").value="";a("gender-boy").checked=
!1;a("gender-girl").checked=!1;a("dob-day").value=-1;a("dob-month").value=-1;a("dob-year").value=-1;f(a("username-container"));f(a("password-container"));f(a("email-container"));f(a("dob-container"));f(a("gender-container"));p(a("header-info"));h.set("oauth-data",!1)},G=function(b){if(b)if(z(),A(),b.neededData&&0===b.neededData.length)f(a(""));else{y();p(a("header-info"));f(a("header-link"));h.set("oauth-data",b);for(var c=0,e=b.neededData.length;c<e;c++)switch(b.neededData[c]){case "password":p(a("password-container"));
f(a("header-info"));p(a("header-link"));break;case "username":p(a("username-container"));break;case "email":p(a("email-container"));break;case "dateOfBirth":p(a("dob-container"));break;case "gender":p(a("gender-container"))}a("header-link-username")&&b.username&&(a("header-link-username").innerHTML=b.username);a("header-link-provider")&&(a("header-link-provider").innerHTML=x[b.provider]);b=n.getAll(".wrong",a(""));if(0<b.length)for(c=0;c<b.length;c++)d.removeClass(b[c],"wrong");for(error in k)k[error]&&
f(k[error]);for(hint in g)g[hint]&&(g[hint].className="tip-sign");q.add("#popup-oauth-register input, #popup-oauth-register select","keydown",function(a){13===("which"in a?a.which:a.keyCode)&&B(a)});p(a(""))}else throw"no data passed to the registration form";},C=function(){m.System.emit("popup.header.close");y();f(a())},D=function(b){a("button").enabled=b;d[b?"removeClass":"addClass"](a("button"),"processing")},H=function(){for(var b=null,c=[],e=null,h=n.getAll(".hinted-container",a("")),f=0;f<h.length;f++){(b=
n.get(".tip-sign",h[f]))&&b.getAttribute("data-signeditem")&&(g[b.getAttribute("data-signeditem")]=b);for(var c=n.getAll(".tip",h[f]),e=0<h[f].getElementsByTagName("input").length?h[f].getElementsByTagName("input"):h[f].getElementsByTagName("select"),l=0;l<c.length;l++)c[l]&&(d.hasClass(c[l],"error")?k[c[l].getAttribute("data-errortype")]=c[l]:tipToggler=w(b,c[l],e))}},A=function(){for(var b=null,c=n.getAll(".hinted-container",a("")),e=0;e<c.length;e++)(b=n.get(".tip",c[e]))&&d.addClass(b,"hidden")},
E=function(a){var c=a.error.type,e=a.field,h=a.loading,f=a.extraData,l=document.getElementById("popup-oauth-register-"+e);if("object"===typeof g[e]){for(error in k)e===error.substr(0,error.indexOf("-"))&&d.addClass(k[error],"hidden");g&&g[e]&&(g[e].className="tip-sign",d[h?"addClass":"removeClass"](g[e],"loading"));a.error?(A(),k[c]&&(d.removeClass(k[c],"hidden"),f&&"function"==typeof k[c].applyExtraData&&k[c].applyExtraData(f)),d.addClass(g[e],"wrong"),l&&d.addClass(l,"wrong")):(d.addClass(g[e],
"right"),l&&d.removeClass(l,"wrong"))}},I=function(){r.validateAll();var b=h.get("oauth-data"),c={oauthToken:b.oauthToken},e;for(e in b.neededData)switch(b.neededData[e]){case "username":if(d.hasClass(a("username"),"wrong"))return!1;c.username=a("username").value;break;case "password":if(d.hasClass(a("password"),"wrong"))return!1;c.password=a("password").value;break;case "email":if(d.hasClass(a("email"),"wrong"))return!1;c.email=a("email").value;break;case "dateOfBirth":if(d.hasClass(a("dob"),"wrong"))return!1;
c.dateOfBirth={year:parseInt(a("dob-year").value),month:parseInt(a("dob-month").value),day:parseInt(a("dob-day").value)};break;case "gender":if(d.hasClass(a("gender"),"wrong"))return!1;c.gender=a("gender").value}return c},J=function(){document.getElementById("popup-oauth-register-close").onclick=function(a){C()};document.getElementById("popup-oauth-register-error-generic-close").onclick=function(a){u(!1)};a("button").onclick=function(a){B(a)}},B=function(b){if("undefined"==typeof a("button").enabled||
a("button").enabled)if(b=I())m.Widget.emit("register.send",b),D(!1)},K=function(){for(var b=1;32>b;b++){var c=document.createElement("option");c.value=b;c.innerHTML=b;a("dob-day").appendChild(c)}for(b=c=(new Date).getFullYear();b>c-101;b--){var e=document.createElement("option");e.value=b;e.innerHTML=b;a("dob-year").appendChild(e)}},F=!1,z=function(){if(!F){F=!0;p(a());v.init("popup-oauth-register-username");v.init("popup-oauth-register-email");v.init("popup-oauth-register-password");H();J();K();
k["username-taken"]&&(k["username-taken"].applyExtraData=function(b){var e=n.get(".alternative-usernames",this);if(e){for(;e.hasChildNodes();)e.removeChild(e.lastChild);for(var d=0;d<b.suggestionList.length;d++){var g=b.suggestionList[d];0<d&&e.appendChild(document.createTextNode(", "));var f=document.createElement("a");f.setAttribute("href","#");f.innerHTML=g;f.onclick=function(b){return function(){a("username").value=b;if("fireEvent"in a("username"))a("username").fireEvent("onchange");else{var c=
document.createEvent("HTMLEvents");c.initEvent("change",!1,!0);a("username").dispatchEvent(c)}}}(g);e.appendChild(f)}}});var b=[{type:"dob",elem:{year:a("dob-year"),month:a("dob-month"),day:a("dob-day")}},{type:"username",elem:a("username")},{type:"email",elem:a("email")},{type:"password",elem:a("password")},{type:"gender",elem:a("gender"),inputs:[a("gender-boy"),a("gender-girl")]}];r.attach(b,E)}};m.Widget.init(function(b){switch(b.name){case "register.open":G(b.data);break;case "register.send":h("api.account.registerOauth",
{oauthToken:b.data.oauthToken,username:b.data.username,email:b.data.email,password:b.data.password,gender:b.data.gender,dateOfBirth:b.data.dateOfBirth},function(c){if(!c.error&&c.auth&&c.auth.token)m.System.emit("popup.header.close"),f(a("")),m.getProperty("use_avatar_picker")?m.System.emit("popup.register.feedback",{type:b.data.password?"link":"register",username:b.data.username}):m.System.emit("registration.finished");else{z();switch(c.error){case "auth":C();u(!0);break;case "badLogin":E({error:{type:"password-invalid"},
field:"password",loading:!1,extraData:!1})}D(!0)}})}})});
/* Games */
Html5Oyunlar("Html5Oyunlar.import",{fullName:"PopupRegister",deps:"FormValidation JSLib SWP DOMSelect DOMEvent Placeholder SWPUtils Cookie".split(" "),module:function(t,k,n,h,g,x,e,y){n.init("popup_register");var A=!1,B=!1,a,m={},p=[],r={},H=0,C=!1,w=!1,v=!1,f=function(a){return document.getElementById(a)},E=function(a,c,d){a&&(a.id="hint-sign-"+H++,g.add("#"+a.id,"mouseover",function(){e.hasClass(a,"icon--form-wrong")||e.removeClass(c,"hidden")}),g.add("#"+a.id,"mouseout",function(){e.addClass(c,"hidden")}));
"object"===typeof d&&d.length||(d=[d]);for(var f=0;f<d.length;f++)g.add("#"+d[f].id,"focus",function(){a&&e.hasClass(a,"icon--form-wrong")||e.removeClass(c,"hidden")}),g.add("#"+d[f].id,"blur",function(){e.addClass(c,"hidden")})},u=function(b){function c(a){g.add(a,"click",function(a){g.preventDefault(a);var b=q.length;for(a=0;a<b;a++)q[a]===this.parentElement?e.removeClass(q[a],"item-active"):(e.addClass(q[a],"item-active"),e.hasClass(q[a],"email-auth")&&f("popup-register-username").focus())})}var d=
f("wdg_popup_register");d.style.visibility="hidden";e.toggleClass(d,"hidden");b||((B=!e.hasClass(d,"hidden"))?n.Widget.emit("open"):n.Widget.emit("close"));setTimeout(function(){I();if(a.usernameEl){if(a.genderEl)var b=a.genderEl.getAttribute("data-gender-default");a.usernameEl.value="";a.emailEl.value="";a.passwordEl.value="";a.genderBoyEl.checked="boy"===b;a.genderGirlEl.checked="girl"===b;switch(b){case "boy":e.addClass(a.genderBoyEl,"is-checked");e.removeClass(a.genderGirlEl,"is-checked");break;
case "girl":e.addClass(a.genderGirlEl,"is-checked"),e.removeClass(a.genderBoyEl,"is-checked")}g.add("#popup-register-gender-boy + .button","click",function(){e.addClass(a.genderBoyEl,"is-checked");e.removeClass(a.genderGirlEl,"is-checked");a.genderBoyEl.checked=!0;a.genderGirlEl.checked=!1});g.add("#popup-register-gender-girl + .button","click",function(){e.addClass(a.genderGirlEl,"is-checked");e.removeClass(a.genderBoyEl,"is-checked");a.genderGirlEl.checked=!0;a.genderBoyEl.checked=!1});w||(a.dobDayEl.value=
-1,a.dobMonthEl.value=-1,a.dobYearEl.value=-1);a.awtConfirmationEl&&(a.awtConfirmationEl.checked=!1);a.subscribeConfirmationEl&&(a.subscribeConfirmationEl.checked=!1);for(var c in p)"function"===typeof p[c].reset&&p[c].reset();b=h.getAll(a.selectors.popup+" .icon--form-wrong");for(c=0;c<b.length;c++)e.removeClass(b[c],"icon--form-wrong");for(error in m)e.addClass(m[error],"hidden");for(hint in r)r[hint].className="tip-sign";/Trident/g.test(window.navigator.userAgent)||(h.get("#"+a.usernameEl.id+"_ph")?
g.trigger("#"+a.usernameEl.id+"_ph","keydown"):a.usernameEl.focus())}d.style.visibility=""},100);var D=h.getAll(".trigger-auth-type"),q=h.getAll(".toggleItem"),l=D.length;for(b=0;b<l;b++)c(D[b])},z=function(b){(a.registerButtonEl.enabled=b)?e.removeClass(a.registerButtonEl,"processsing"):e.addClass(a.registerButtonEl,"processsing")},J=function(){for(var b=h.getAll(a.selectors.popup+" "+a.selectors.tipSign),c=h.getAll(a.selectors.popup+" "+a.selectors.tip+".help"),d=h.getAll(a.selectors.popup+" "+
a.selectors.tip+".error"),f=h.get(a.selectors.popup+" "+a.selectors.tip+".input"),q,l=0;l<a.hintedContainers.length;l++)if(q=0<a.hintedContainers[l].getElementsByTagName("input").length?a.hintedContainers[l].getElementsByTagName("input"):a.hintedContainers[l].getElementsByTagName("select"),"popup-register-dob"===a.hintedContainers[l].id)E(null,f,q),e.addClass(f,"hidden");else{var g=b[l]?b[l]:null;if(g&&0<g.getAttribute("title").length){r[g.getAttribute("title")]=g;for(var k=0;k<c.length;k++)e.addClass(c[k],
"hidden"),c[k].getAttribute("rel")===g.getAttribute("title")&&E(g,c[k],q)}}for(b=0;b<d.length;b++)d[b].getAttribute("title")&&(m[d[b].getAttribute("title")]=d[b])},K=function(a){var c=a.error.type,d=a.field,f=a.loading,g=a.extraData,l=document.getElementById("popup-register-"+d);for(error in m)d===error.substr(0,error.indexOf("-"))&&e.addClass(m[error],"hidden");if(a.error){if(m[c]){if(!1===v||d===v)v=d,e.removeClass(m[c],"hidden");g&&"function"==typeof m[c].applyExtraData&&m[c].applyExtraData(g)}r[d]&&
(r[d].className="tip-sign icon--form-wrong");l&&!e.hasClass(l,"icon--form-wrong")&&e.addClass(l,"wrong")}else f?r[d].className="tip-sign loading":r[d]&&(r[d].className="tip-sign icon--form-right"),l&&e.removeClass(l,"wrong"),!0===a.correct&&d===v&&(v=!1);if(g&&"function"==typeof p[d])p[d](g);"dob"===a.field&&!w&&a.error&&"dob-coppa-underage"===a.error.type&&(y.setItem({key:"registrationLocked",value:a.userData.day+"."+(a.userData.month+1)+"."+a.userData.year}),w=!0,F())},L=function(){g.add(f("popup-register-facebook"),
"click",function(){G("facebook")});g.add(f("popup-register-google"),"click",function(){G("google")});g.add(f("register-alreadyuser"),"click",function(a){g.preventDefault(a);u();n.System.emit("popup.login.open",{})})},M=function(){if(a.usernameEl){var b=[{type:"username",elem:a.usernameEl},{type:"email",elem:a.emailEl},{type:"password",elem:a.passwordEl},{type:"dob",elem:{year:a.dobYearEl,month:a.dobMonthEl,day:a.dobDayEl},coppaEnabled:C},{type:"gender",elem:a.genderEl,inputs:[a.genderBoyEl,a.genderGirlEl]}];
a.awtConfirmationEl&&b.push({type:"agree-with-terms",elem:a.awtConfirmationEl});t.attach(b,K)}},N=function(){document.getElementById("popup-register-close").onclick=function(a){u();n.System.emit("popup.closed",{type:"register"})};var b=document.getElementById("popup-register-close-button");b&&(b.onclick=function(a){u();n.System.emit("popup.closed",{type:"register"})});if(b=document.getElementById("popup-register-email-taken-login"))b.onclick=function(b){g.preventDefault(b);g.trigger(a.alreadyUserLinkEl,
"click")};a.registerButtonEl&&(a.registerButtonEl.onclick=function(b){g.preventDefault(b);if("undefined"==typeof a.registerButtonEl.enabled||a.registerButtonEl.enabled)t.validateAll(),0===h.getAll(".hinted.wrong").length&&0===h.getAll(".hinted-container.wrong").length&&(b=!0,a.subscribeConfirmationEl&&(b=a.subscribeConfirmationEl.checked?!0:!1),k("api.account.register",{username:a.usernameEl.value,email:a.emailEl.value,password:a.passwordEl.value,gender:a.genderBoyEl.checked?"m":"f",dateOfBirth:{year:parseInt(a.dobYearEl.value,
10),month:parseInt(a.dobMonthEl.value,10),day:parseInt(a.dobDayEl.value,10)},subscribe:b},function(b){!b.error&&b.auth&&b.auth.token?(u(),n.System.emit("popup.register.feedback",{type:"register",username:a.usernameEl.value})):z(!0)}),z(!1))})},O=function(){if(a.dobDayEl)for(var b=1;32>b;b++){var c=document.createElement("option");c.value=b;c.innerHTML=b;a.dobDayEl.appendChild(c)}if(a.dobYearEl)for(b=c=(new Date).getFullYear();b>c-101;b--){var d=document.createElement("option");d.value=b;d.innerHTML=
b;a.dobYearEl.appendChild(d)}},P=function(b,c){var d=(b.target||b.srcElement).getAttribute("full-suggestion");null!=d&&(a.emailEl.value=d,a.emailEl.focus(),"function"===typeof c&&c.call())},G=function(a){u();n.System.emit("popup.oauth.open",{provider:a})},Q=function(){var a=y.getItem("registrationLocked"),c=!!a;c&&(y.setItem({key:"registrationLocked",value:a}),w=!0,F(a));return c},F=function(b){b&&(b=b.split("."),a.dobDayEl.value=b[0],a.dobMonthEl.value=b[1],a.dobYearEl.value=b[2]);a.dobDayEl.setAttribute("disabled",
"true");a.dobMonthEl.setAttribute("disabled","true");a.dobYearEl.setAttribute("disabled","true");b=h.get(a.selectors.popup);e.addClass(b,"coppa-denied");h.get("#popup-register-button").style.display="none";e.addClass(a.dobEl,"coppa-wrong")},I=function(){A||(A=!0,a||(a={passwordEl:f("popup-register-password"),genderEl:f("popup-register-gender"),genderBoyEl:f("popup-register-gender-boy"),emailEl:f("popup-register-email"),genderGirlEl:f("popup-register-gender-girl"),usernameEl:f("popup-register-username"),
dobEl:f("popup-register-dob"),dobDayEl:f("popup-register-dob-day"),dobMonthEl:f("popup-register-dob-month"),dobYearEl:f("popup-register-dob-year"),awtConfirmationEl:f("popup-register-agree-with-terms-element"),subscribeConfirmationEl:f("popup-register-subscribe-element"),popupRegisterEl:f("wdg_popup_register"),alreadyUserLinkEl:f("register-alreadyuser"),registerButtonEl:f("popup-register-button"),gameidEl:f("popup-register-gameid"),hintedContainers:h.getAll("#wdg_popup_register .hinted-container"),
selectors:{popup:"#wdg_popup_register",hintedContainers:".hinted-container",tipSign:".tip-sign",tip:".tip"}}),J(),N(),O(),(C="true"===h.get(a.selectors.popup).getAttribute("data-coppa-enabled"))&&Q(),L(),M(),x.init("popup-register-username"),x.init("popup-register-email"),x.init("popup-register-password"),m["username-taken"]&&(m["username-taken"].applyExtraData=function(b){for(var c=h.get(".alternative-usernames",this);c.hasChildNodes();)c.removeChild(c.lastChild);for(var d=0;d<b.suggestionList.length;d++){var e=
b.suggestionList[d];0<d&&c.appendChild(document.createTextNode(", "));var f=document.createElement("a");f.setAttribute("href","#");f.innerHTML=e;f.onclick=function(b){return function(){a.usernameEl.value=b;g.trigger(a.usernameEl,"change")}}(e);c.appendChild(f)}}),p.email=function(a){if(a.suggestionList&&0<a.suggestionList.length){for(var c=document.getElementById("popup-register-email-extradata"),d=c.getAttribute("base-text"),f=c.getAttribute("list-separator"),e=" ",g=0;g<a.suggestionList.length&&
2>g;g++){0<g&&(e+=f);var h=a.suggestionList[g],k=h.split("@"),e=e+('<a href="#" full-suggestion="'+h+'"> ...@'+k[1]+"</a>")}c.innerHTML=d+(e+"?");c.style.display="block";c.onclick=function(a){P(a||window.event,function(){p.email.reset()})}}else p.email.reset()},p.email&&(p.email.reset=function(){var a=document.getElementById("popup-register-email-extradata");a.style.display="none";a.innerHTML=""}))};return{isOpen:function(){return B},toggleRegistrationPopup:u,toggleRegisterButton:z}}});Html5Oyunlar({waiton:"Html5Oyunlar.loaded"},["PopupRegister","SWP","DOMSelect"],function(t,k,n){k.init("popup_register");k.System.init(function(h){switch(h.name){case "popup.login.open":t.isOpen()&&t.toggleRegistrationPopup(!0);break;case "popup.register.open":n.get("#popup-register-close")?t.toggleRegistrationPopup():k.Widget.refresh({show_popup_contents:!0},{callback:function(){setTimeout(function(){t.toggleRegistrationPopup()},0)}})}});k.Widget.init(function(h){switch(h.name){case "open":k.System.emit("gi.game.hide");
k.System.emit("popup.header.open");break;case "close":k.System.emit("gi.game.show"),k.System.emit("popup.header.close")}})});
/* Games */
Html5Oyunlar({name:"wdg_popup_register_feedback",waiton:"Html5Oyunlar.loaded"},"SWPUtils SWP SWPEvent JSLib DOMSelect PopupRegisterFeedback PopupRegisterFeedbackHelper Portal".split(" "),function(f,b,g,k,c,d,m,q){function h(a){k("api.user.get",function(b){a(b)})}b.init("popup_register_feedback");var l=b.getProperty("show_popup_contents"),e=function(){var a=!1;return function(){a||(m.init(".wdg_popup_register_feedback"),d.init({container:".wdg_popup_register_feedback",elements:{closeButton:"popup-register-feedback-close"}}),
a=!0)}}();b.System.init(function(a){var k,n,c,g=a.body&&a.body.type,f=a.body&&a.body.username;switch(a.name){case "popup.register.feedback":var r=function(){e();n={username:f||""};c="";h(function(a){if(!a.error&&a.userInfo){n.username=a.userInfo.name||n.username;c=a.userInfo.avatarUrl;a=a.userInfo.guid;q.get("siteid");var e=document.getElementById("wdg_popup_register_feedback_version"),f=document.getElementById("wdg_prf_campaignid"),l=document.getElementById("wdg_prf_productid"),h=document.getElementById("wdg_prf_conversiontype");
if(null!==e&&"object"==typeof e&&""!=f.value&&""!=l.value&&""!=h.value){var p=document.createElement("IFRAME");p.setAttribute("src","/wdg/popup_register_feedback-"+e.value+"/tt/conversion.html?campaignID="+f.value+"&productID="+l.value+"&conversionType="+h.value+"&GUID="+a+"&transactionID="+a);p.style.width="1px";p.style.height="1px";document.body.appendChild(p)}}k=m.whichPopupToShow(g,c);d.open(k,n);b.System.emit("popup.header.open")})};l?!0===l&&r():(l="loading",b.Widget.refresh({show_popup_contents:!0},
{callback:function(){setTimeout(function(){l=!0;r()},0)}}))}});g.listen("popup.registration.feedback.closed",function(){b.System.emit("registration.finished");b.System.emit("popup.header.close")})});Html5Oyunlar("Html5Oyunlar.import",{name:"PopupRegisterFeedbackHelper",deps:["DOMSelect"],module:function(f){function b(){var b=!1,c=f.get(g);c&&(b="true"===c.getAttribute("data-on-social-game-page"));return b}var g;return{init:function(b){g=b},whichPopupToShow:function(k,c){var d;switch(k){case "link":b()?d="link-social":(d=(c||"").split("/").pop(),d="dummy_small.png"!==d&&"dummy_small.gif"!==d?"link-regular":"link-regular-without-avatar");break;default:case "register":d=b()?"registration-social":"registration-regular"}return d}}}});Html5Oyunlar("Html5Oyunlar.import",{name:"PopupRegisterFeedback",deps:["SWPEvent","SWPUtils","Utils","DOMSelect","DOMEvent"],module:function(f,b,g,k,c){var d,m,q=function(e){c.add(d,"click",function(a){b.hasClass(a.target||a.srcElement,e.closeButton)&&h()})},h=function(){f.emit("popup.registration.feedback.closed");b.addClass(m,"hidden")},l=function(){var e=k.getAll(d+" > article");g.each(e,function(a,d,e){b.hasClass(a,"hidden")||b.addClass(a,"hidden")})};return{init:function(b){d=b.container;m=k.get(d);
q(b.elements)},open:function(e,a){if(e){l();var c,f,g,h;if(a){g=k.get(d+" > #"+e);h=g.innerHTML;for(c in a)a.hasOwnProperty(c)&&(f=new RegExp("\\["+c+"\\]","g"),h=h.replace(f,a[c]));g.innerHTML=h}(c=k.get(d+" > #"+e))&&b.removeClass(c,"hidden");b.removeClass(m,"hidden")}},close:h}}});
/* Games */
Html5Oyunlar(["SWP","SWPUtils","Net","DOMEvent"],function(n,d,z,g){n.init("search_bar");var r=window.document,t=r.getElementById("wdg_search_bar"),A=n.getProperty("microservice_url"),u=function(){var a={};return{set:function(c,b){a[c]=b},get:function(c){return a[c]||!1}}}(),h=function(a,c){c=c||t;return c.querySelector(a)},v=function(a){return h(".template",a).outerHTML.replace("data-src","src").replace(' class="template"',"")},e=h("#search-term"),f=h(".search-suggestions"),p=h(".labels"),k=h("ul",p),
B=v(k),p=h(".games"),l=h("ul",p),C=v(l),b=-1;if(f){var m=function(){var a;!r.getElementsByClassName&&e.createTextRange&&(e.select(),a=e.createTextRange(),a.collapse(!1),a.select())},w,q=function(){k.innerHTML="";l.innerHTML="";d.removeClass(f,"visible")},D=function(a){var c=a.q,b=u.get(c);b?(x({searchTerm:c,data:b}),m()):z.send({url:A,data:a,onsuccess:function(a){u.set(c,a);x({searchTerm:c,data:a});m()},onerror:function(a){d.error(a)}},function(){})},y=function(){var a=e.value,a=20<a.length?a.substring(0,
20):a;2<=a.length?D({q:encodeURIComponent(a)}):(q(),m())},x=function(a){a=JSON.parse(a.data);var c=function(a,c){return a.replace(/{(.*?)}/g,function(a,b){return c[b]})},b=function(a,b){return a.map(function(a){return c(b,a)}).join("")};q();k.innerHTML=b(a.suggestions.label.slice(0,3),B);l.innerHTML=b(a.suggestions.game.slice(0,5),C);""===k.innerHTML&&""===l.innerHTML||d.addClass(f,"visible");""!==k.innerHTML?d.addClass(f,"has-labels"):d.removeClass(f,"has-labels");""!==l.innerHTML?d.addClass(f,"has-games"):
d.removeClass(f,"has-games")};g.add(t,"submit",function(a){var c=e.value,d;d=c.substr(0,1E3);Html5Oyunlar("tracker.event.express",{data:{eventCategory:"search",eventAction:"application",eventLabel:"submit",properties:{searchTerm:d}}});0<=b?(g.preventDefault(a),a=f.querySelectorAll("li")[b].querySelector("a"),window.location=a.href):2<=c.length&&e.placeholder!==c&&!~c.indexOf("@")?n.System.emit("user.search.request",{searchTerm:c}):g.preventDefault(a)});g.add(e,"keyup",function(a){38!==a.keyCode&&40!==
a.keyCode&&y()});g.add(e,"keydown",function(a){switch(a.keyCode){case 38:g.preventDefault(a);a=f.querySelectorAll("li");d.removeClass(a[b],"is-selected");b=0<b?--b:a.length-1;d.addClass(a[b],"is-selected");break;case 40:g.preventDefault(a);a=f.querySelectorAll("li");d.removeClass(a[b],"is-selected");b=++b%a.length;d.addClass(a[b],"is-selected");break;case 13:break;default:b=-1}});g.add(e,"focus",function(){window.clearTimeout(w);y()});g.add(e,"blur",function(){w=window.setTimeout(function(){q();m()},
1E3)})}});
/* Games */
Html5Oyunlar(["SWP","DOMEvent","Net","Cookie"],function(b,e,g,c){b.init("theme_settings");var d=window,f=d.document.getElementById("wdg_theme_settings"),h=f.querySelector(".toggle"),k=b.getProperty("siteid"),l=b.getProperty("user_logged_in"),m=b.getProperty("guid"),n=b.get("Html5Oyunlar.module.spapi.backend"),p=function(a){l?g.send({url:n+"v1/theme/user/"+k+"/"+m+"/all",type:"PUT",dataType:"json",data:JSON.stringify({theme:a,enabled:!0}),headers:{"x-auth-token":c.getItem("token")}},function(){}):(c.removeItem({key:"swp_theme",
path:"/"+d.location.pathname.split("/")[1]||""}),c.setItem({key:"swp_theme",value:a,expires:"never",path:"/"}))};e.add(h,"click",function(){b.Utils.toggleClass(f,"is-open")});e.add(".dropdown-box","click",function(a){a=a||d.event;a=a.target||a.srcElement;if(a=a.getAttribute("data-theme")||a.parentNode.getAttribute("data-theme"))b.System.emit("theme.changed",{theme:a}),p(a)})});
/* Games */
Html5Oyunlar(["SWP","SWPUtils","DOMEvent","JSLib"],function(c,f,e,m){var d=document.getElementById("wdg_user_status"),g=document.getElementById("logged-user-avatar"),a=d.querySelector(".unit-counter"),h=!1,k=function(){h=!0;a&&m("api.notification.count",function(b){b.count?(a.innerHTML=b.count,f.removeClass(a,"is-hidden")):f.addClass(a,"is-hidden")})},l=function(){h||k()};c.init("user_status");e.add(d,"click",function(b){for(var a=b.target;!a.id;)a=a.parentNode;switch(a.id){case "login-button-nav":c.System.emit("popup.login.open",
{});b.preventDefault();break;case "logout-button-nav":c.System.emit("auth.logout.request",{}),b.preventDefault()}});a&&(e.add(d,"click",l),e.add(d,"mouseover",l));c.System.init(function(a){switch(a.name){case "avatar.update.current":g&&(g.src=a.body.avatarUrl);break;case "system.notification.update.amount":k()}})});